### ISSUE TITLE
Node 0.8 not supported?

### ISSUE THREAD

**Issue by samholmes** [deoxxa/jesus#3]
Doesn't work in Node v0.8?

```
$ npm install -g jesus
npm http GET https://registry.npmjs.org/jesus
npm http 304 https://registry.npmjs.org/jesus
npm http GET https://registry.npmjs.org/burro
npm http GET https://registry.npmjs.org/pillion
npm http GET https://registry.npmjs.org/asciitable
npm http GET https://registry.npmjs.org/vague-time
npm http 200 https://registry.npmjs.org/burro
npm http 200 https://registry.npmjs.org/pillion
npm http 200 https://registry.npmjs.org/asciitable
npm http GET https://registry.npmjs.org/burro/-/burro-0.4.13.tgz
npm http GET https://registry.npmjs.org/pillion/-/pillion-0.0.7.tgz
npm http GET https://registry.npmjs.org/asciitable/-/asciitable-0.0.7.tgz
npm http 200 https://registry.npmjs.org/vague-time
npm http GET https://registry.npmjs.org/vague-time/-/vague-time-0.5.4.tgz
npm http 200 https://registry.npmjs.org/burro/-/burro-0.4.13.tgz
npm http 200 https://registry.npmjs.org/asciitable/-/asciitable-0.0.7.tgz
npm http 200 https://registry.npmjs.org/pillion/-/pillion-0.0.7.tgz
npm http 200 https://registry.npmjs.org/vague-time/-/vague-time-0.5.4.tgz
npm WARN engine pillion@0.0.7: wanted: {"node":"~0.9.12 || ~0.10.0"} (current: {"node":"v0.8.22","npm":"1.2.14"})
npm WARN engine burro@0.4.13: wanted: {"node":"~0.10.12"} (current: {"node":"v0.8.22","npm":"1.2.14"})
npm http GET https://registry.npmjs.org/bun
npm http 200 https://registry.npmjs.org/bun
npm http GET https://registry.npmjs.org/bun/-/bun-0.0.6.tgz
npm http 200 https://registry.npmjs.org/bun/-/bun-0.0.6.tgz
npm WARN engine bun@0.0.6: wanted: {"node":"~0.10.12"} (current: {"node":"v0.8.22","npm":"1.2.14"})
/usr/local/bin/jesus -> /usr/local/lib/node_modules/jesus/bin/jesus
npm WARN unmet dependency /usr/local/lib/node_modules/acs/node_modules/socket.io/node_modules/socket.io-client requires uglify-js@'1.2.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/acs/node_modules/uglify-js,
npm WARN unmet dependency which is version 1.3.2
jesus@0.0.11 /usr/local/lib/node_modules/jesus
├── asciitable@0.0.7
├── pillion@0.0.7
├── vague-time@0.5.4
└── burro@0.4.13 (bun@0.0.6)
```

```
$ jesus
/usr/local/lib/node_modules/jesus/node_modules/burro/lib/encoder.js:6
Encoder.prototype = Object.create(stream.Transform.prototype, {constructor: {v
                                                  ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/jesus/node_modules/burro/lib/encoder.js:6:51)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/jesus/node_modules/burro/lib/burro.js:1:99)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
```

**Comment by deoxxa** [comment]
Correct. Node 0.10 is the current stable, and I don't want to have to target legacy node releases.
