### ISSUE TITLE
Not supported in 0.10

### ISSUE THREAD

**Issue by samholmes** [deoxxa/jesus#4]
```
ϟ ~ sudo npm install -g jesus
Password:
npm http GET https://registry.npmjs.org/jesus
npm http 304 https://registry.npmjs.org/jesus
npm http GET https://registry.npmjs.org/burro
npm http GET https://registry.npmjs.org/pillion
npm http GET https://registry.npmjs.org/asciitable
npm http GET https://registry.npmjs.org/vague-time
npm http 304 https://registry.npmjs.org/asciitable
npm http 304 https://registry.npmjs.org/burro
npm http 304 https://registry.npmjs.org/pillion
npm http 304 https://registry.npmjs.org/vague-time
npm http GET https://registry.npmjs.org/bun
npm http 304 https://registry.npmjs.org/bun
/usr/local/bin/jesus -> /usr/local/lib/node_modules/jesus/bin/jesus
npm WARN package.json exterminate@1.3.0 No repository field.
npm WARN package.json connect-mongo@0.1.9 No repository field.
npm WARN package.json string@1.1.0 homepage field must be a string url. Deleted.
npm WARN package.json uglify-js@2.2.5 No repository field.
npm WARN package.json uglify-js@2.2.5 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json jsdom@0.5.1 No repository field.
npm WARN package.json jsdom@0.5.1 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json sprintf@0.1.1 No repository field.
npm WARN package.json bytes@0.0.1 No repository field.
npm WARN package.json formidable@1.0.11 No repository field.
npm WARN package.json fresh@0.0.1 No repository field.
npm WARN package.json range-parser@0.0.4 No repository field.
npm WARN package.json fresh@0.1.0 No repository field.
npm WARN package.json methods@0.0.1 No repository field.
npm WARN package.json send@0.1.0 No repository field.
npm WARN package.json policyfile@0.0.4 No repository field.
npm WARN package.json policyfile@0.0.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json JSV@4.0.2 No repository field.
npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json amdefine@0.0.4 No repository field.
npm WARN package.json eyes@0.1.8 No repository field.
npm WARN package.json github-url-from-git@1.1.1 No repository field.
npm WARN package.json bytes@0.1.0 No repository field.
npm WARN package.json pause@0.0.1 No repository field.
npm WARN package.json send@0.0.4 No repository field.
npm WARN package.json hiredis@0.1.15 No repository field.
npm WARN package.json callsite@1.0.0 No repository field.
npm WARN package.json faye-websocket@0.4.0 No repository field.
npm WARN package.json faye-websocket@0.4.0 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json rbytes@0.0.2 No repository field.
npm WARN package.json assert-plus@0.1.2 No repository field.
npm WARN package.json ctype@0.5.2 No repository field.
npm WARN unmet dependency /usr/local/lib/node_modules/acs/node_modules/socket.io/node_modules/socket.io-client requires uglify-js@'1.2.5' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/acs/node_modules/uglify-js,
npm WARN unmet dependency which is version 1.3.2
jesus@0.0.11 /usr/local/lib/node_modules/jesus
├── asciitable@0.0.7
├── pillion@0.0.7
├── vague-time@0.5.4
└── burro@0.4.13 (bun@0.0.6)
```

```
ϟ ~/Desktop/server jesus server server.js 
ϟ ~/Desktop/server jesus list

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ENOENT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

**Comment by pawmart** [comment]
getting the same error ;(

**Comment by deoxxa** [comment]
The problem is that there's no "server" command. There's "listen" and there's "daemon", of which you probably want "daemon". Check out the readme, it's all in there :)
